/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Clipper: typeof import('./src/components/custom/Clipper.vue')['default']
    ClipperTable: typeof import('./src/components/business/ClipperTable/ClipperTable.vue')['default']
    Group: typeof import('./src/components/siyuan/setting/Group.vue')['default']
    HomePage: typeof import('./src/components/business/HomePage/HomePage.vue')['default']
    Input: typeof import('./src/components/siyuan/setting/Input.vue')['default']
    Item: typeof import('./src/components/siyuan/setting/Item.vue')['default']
    MiniItem: typeof import('./src/components/siyuan/setting/MiniItem.vue')['default']
    Panel: typeof import('./src/components/siyuan/setting/Panel.vue')['default']
    Panels: typeof import('./src/components/siyuan/setting/Panels.vue')['default']
    Setting: typeof import('./src/components/custom/Setting.vue')['default']
    ShowTips: typeof import('./src/components/custom/ShowTips.vue')['default']
    Svg: typeof import('./src/components/siyuan/misc/Svg.vue')['default']
    Table: typeof import('./src/components/custom/Table.vue')['default']
    Tabs: typeof import('./src/components/siyuan/setting/Tabs.vue')['default']
    Tips: typeof import('./src/components/siyuan/dialog/Tips.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
